# Requires actual Salmon quant.sf files, not a matrix of FPKM/TPM values.
args <- commandArgs(trailingOnly = TRUE)
if (length(args) < 6 || length(args) > 7) stop("Usage: Rscript tximport_deseq2.R quantfiles.tsv tx2gene.tsv metadata.tsv reference test outdir [covariates]")
script <- sub("^--file=", "", commandArgs()[grepl("^--file=", commandArgs())][1])
source(file.path(dirname(normalizePath(script)), "review_design.R"))
suppressPackageStartupMessages({library(tximport); library(DESeq2)})
manifest <- read.delim(args[1], stringsAsFactors = FALSE, check.names = FALSE)
if (!all(c("sample", "quant_file") %in% names(manifest)) || anyNA(manifest) || anyDuplicated(manifest$sample) || any(!nzchar(manifest$sample))) stop("quantfiles.tsv requires distinct sample and quant_file entries")
files <- setNames(manifest$quant_file, manifest$sample)
if (anyDuplicated(normalizePath(files, mustWork = TRUE))) stop("Every biological sample must have its own quantification file")
mapping <- read.delim(args[2], colClasses = "character", check.names = FALSE)
if (ncol(mapping) != 2 || anyNA(mapping) || any(!nzchar(unlist(mapping))) || anyDuplicated(mapping[[1]])) stop("tx2gene.tsv requires unique transcript IDs and nonempty gene IDs from the same annotation used for Salmon")
d <- review_design(args[3], names(files), args[4], args[5], if (length(args) == 7) args[7] else "")
for (file in files) {
  q <- read.delim(file, check.names = FALSE)
  if (!all(c("Name", "Length", "EffectiveLength", "TPM", "NumReads") %in% names(q)) || anyDuplicated(q$Name) || any(!q$Name %in% mapping[[1]])) stop("Require genuine Salmon quant.sf files and complete matching transcript-to-gene annotation")
  numeric_columns <- c("Length", "EffectiveLength", "TPM", "NumReads")
  if (!all(vapply(q[numeric_columns], is.numeric, logical(1))) || any(!is.finite(as.matrix(q[numeric_columns]))) || any(q$Length <= 0) || any(q$EffectiveLength <= 0) || any(q$TPM < 0) || any(q$NumReads < 0)) stop("Salmon quantification contains invalid lengths or abundance/count values")
}
txi <- tximport(files, type = "salmon", tx2gene = mapping, countsFromAbundance = "no")
dds <- DESeqDataSetFromTximport(txi, colData = d$meta, design = d$formula)
keep <- rowSums(counts(dds) >= 10) >= min(table(d$meta$condition))
if (sum(keep) < 20) stop("Fewer than 20 retained genes")
dds <- DESeq(dds[keep, ])
res <- results(dds, contrast = c("condition", args[5], args[4]), alpha = 0.05)
out <- args[6]; dir.create(out, recursive = TRUE, showWarnings = FALSE)
saveRDS(dds, file.path(out, "dds_with_length_offsets.rds"))
write.table(data.frame(gene = rownames(res), as.data.frame(res)), file.path(out, "deseq2_tximport_results.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
write.table(d$matrix, file.path(out, "design_matrix.tsv"), sep = "\t", quote = FALSE)
pdf(file.path(out, "MA.pdf")); plotMA(res); dev.off()
write_provenance(out, "Salmon + tximport + DESeqDataSetFromTximport", c(args[1:3], unname(files)), c(paste("Contrast:", args[5], "minus", args[4]), paste("Design:", deparse(d$formula)), "Estimated counts and sample-dependent length corrections retained in the RDS. Do not export rounded TPM/FPKM into the raw-count upload.", "Transcript mapping must be from the same organism and annotation/index release; record index provenance separately."))
