"""Downloadable deterministic NGS demonstration datasets.

These endpoints expose the exact synthetic FASTQ content generated by the NGS v2
preview profiles so a user can inspect/download the input as well as run it with one
click. The generated files are intentionally small and are not biological validation
material.
"""
from __future__ import annotations

import os
import shutil
from pathlib import Path

from fastapi import APIRouter, HTTPException
from fastapi.responses import PlainTextResponse

from app.routers.ngs_v2 import _DEMO_PROFILES, _write_demo_fastqs

router = APIRouter(prefix="/api/ngs/v2/demos", tags=["ngs-v2-demos"])


def _profile_or_404(profile: str) -> dict:
    item = _DEMO_PROFILES.get(profile)
    if not item:
        raise HTTPException(status_code=404, detail="NGS demo dataset not found")
    return item


def _generated(profile: str) -> tuple[list[str], dict, dict]:
    _profile_or_404(profile)
    return _write_demo_fastqs(profile)


@router.get("/catalog")
def demo_catalog():
    """User-facing catalog with run purpose and downloadable-file links."""
    rows = []
    purposes = {
        "wgs-truth-control": "Variant calling and expected-vs-observed functional control",
        "wgs-clean": "Clean paired-end WGS baseline",
        "wgs-mixed-quality": "QC/trimming warning demonstration",
        "wes-small": "Compact WES-style paired-end workflow demonstration",
    }
    for profile, item in _DEMO_PROFILES.items():
        rows.append({
            "id": profile,
            "label": item["label"],
            "assay": item["assay"],
            "description": item["description"],
            "purpose": purposes.get(profile, "NGS workflow demonstration"),
            "read_pairs": int(item["read_pairs"]),
            "read_length": 150,
            "paired_end": True,
            "truth_bearing": bool(item.get("truth_bearing")),
            "downloads": {
                "r1": f"/api/ngs/v2/demos/{profile}/download/r1",
                "r2": f"/api/ngs/v2/demos/{profile}/download/r2",
                **({"reference": f"/api/ngs/v2/demos/{profile}/download/reference"} if item.get("truth_bearing") else {}),
            },
        })
    return {"demos": rows}


@router.get("/{profile}/download/{kind}")
def download_demo_file(profile: str, kind: str):
    """Return one deterministic FASTQ mate or the synthetic truth reference as text."""
    if kind not in {"r1", "r2", "reference"}:
        raise HTTPException(status_code=404, detail="Demo file not found")
    paths: list[str] = []
    directory: str | None = None
    try:
        paths, public, runtime = _generated(profile)
        directory = str(Path(paths[0]).parent) if paths else None
        if kind in {"r1", "r2"}:
            index = 0 if kind == "r1" else 1
            if len(paths) <= index:
                raise HTTPException(status_code=404, detail="Demo FASTQ mate not found")
            path = paths[index]
            text = Path(path).read_text(encoding="utf-8")
            filename = f"{profile}_{kind.upper()}.fastq"
            return PlainTextResponse(
                content=text,
                media_type="text/plain; charset=utf-8",
                headers={"Content-Disposition": f'attachment; filename="{filename}"'},
            )

        reference = runtime.get("reference_seq")
        contig = runtime.get("contig") or "chrSynthetic"
        if not reference:
            raise HTTPException(status_code=404, detail="This demo does not define a standalone synthetic truth reference")
        fasta = f">{contig} {public.get('label', profile)}\n"
        fasta += "\n".join(reference[i:i + 80] for i in range(0, len(reference), 80)) + "\n"
        return PlainTextResponse(
            content=fasta,
            media_type="text/plain; charset=utf-8",
            headers={"Content-Disposition": f'attachment; filename="{profile}_reference.fasta"'},
        )
    finally:
        if directory and os.path.isdir(directory):
            shutil.rmtree(directory, ignore_errors=True)
