"""Automated codebase documentation generator (Component 17).

Re-imports every registered router in isolation (skipping any router whose
import chain needs heavy optional deps, e.g. reportlab), merges them into a
throwaway FastAPI app, and writes API docs to the docs/ folder. Also emits the
engine registry and dataset catalog documentation. Deterministic for CI/docs
parity — generated .md files are committed.
"""

from __future__ import annotations

import importlib
import os
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from fastapi import APIRouter, FastAPI

BACKEND = Path(__file__).resolve().parents[1]
MAIN_PY = BACKEND / "app" / "main.py"
DOCS_OUT = BACKEND / "docs"


def _router_modules() -> list[str]:
    src = MAIN_PY.read_text(encoding="utf-8")
    import_line = next(l for l in src.splitlines() if l.startswith("from app.routers import"))
    tokens = re.sub(r"^from app\.routers import ", "", import_line).split(",")
    return [t.strip() for t in tokens if t.strip()]


def _router_prefixes() -> dict[str, str]:
    """Map router module -> include_router prefix as declared in main.py."""
    src = MAIN_PY.read_text(encoding="utf-8")
    prefixes: dict[str, str] = {}
    for line in src.splitlines():
        m = re.match(r'app\.include_router\((\w+)\.router(?:,\s*prefix\s*=\s*"([^"]*)")?', line.strip())
        if m:
            name, prefix = m.group(1), m.group(2)
            prefixes[name] = prefix or ""
    return prefixes


def _build_app() -> FastAPI:
    app = FastAPI()
    loaded: list[str] = []
    prefixes = _router_prefixes()
    for name in _router_modules():
        if not name:
            continue
        try:
            mod = importlib.import_module(f"app.routers.{name}")
        except Exception as e:  # noqa: BLE001 — optional deps (reportlab etc.)
            print(f"  skip router '{name}': {type(e).__name__}: {e}")
            continue
        router = getattr(mod, "router", None)
        if isinstance(router, APIRouter):
            app.include_router(router, prefix=prefixes.get(name))
            loaded.append(name)
    return app


def _http_routes(app: FastAPI) -> list[tuple[str, str, str]]:
    rows = []
    for route in app.routes:
        for method in getattr(route, "methods", []) or []:
            if method in {"HEAD", "OPTIONS"}:
                continue
            doc = (getattr(route, "endpoint", None).__doc__ or "").strip().splitlines()
            rows.append((method, getattr(route, "path", "/"), doc[0] if doc else ""))
    return sorted(rows, key=lambda r: (r[1], r[0]))


def _api_md(rows: list[tuple[str, str, str]]) -> str:
    lines = ["# BioNexus API (automatically generated)", "",
             "> Generated by `scripts/generate_docs.py` — do not edit by hand.", ""]
    for method, path, doc in rows:
        lines.append(f"- `{method}` `{path}` — {doc}")
    lines.append("")
    return "\n".join(lines)


def _engines_md() -> str:
    from app.engines import ENGINES
    lines = ["# BioNexus Scientific Engines", "",
             "> Generated — do not edit by hand.", ""]
    for name in sorted(ENGINES):
        e = ENGINES[name]
        d = e.describe()
        lines += [f"## {name}", "",
                  f"- **Version:** {d.get('version')}",
                  f"- **Tool:** {d.get('tool')} ({d.get('tool_version') or 'version detected at runtime'})",
                  f"- **Databases:** {', '.join(d.get('databases') or [])}",
                  f"- **Parameters:** {d.get('parameters')}",
                  f"- **Benchmarks:** {', '.join(d.get('benchmarks') or [])}",
                  f"- **Exports:** {', '.join(d.get('export_formats') or [])}",
                  f"- **Figures:** {', '.join(d.get('figure_formats') or [])}",
                  "", f"- **Citations:**", *[f"  - {c}" for c in (d.get('citations') or [])], ""]
    return "\n".join(lines)


def _datasets_md() -> str:
    from app.services.dataset_library import list_datasets
    lines = ["# Dataset Library", "", "> Generated — do not edit by hand.", ""]
    for d in list_datasets():
        lines += [f"## {d['name']}",
                  f"- **Category:** {d.get('category')}",
                  f"- **Type:** {d.get('type')} · date {d.get('date')} · version {d.get('version')}",
                  f"- **Records:** {d.get('records_count')}",
                  f"- **Description:** {d.get('description')}",
                  f"- **Citation:** {d.get('citation')}", ""]
    return "\n".join(lines)


def main() -> int:
    os.makedirs(DOCS_OUT, exist_ok=True)
    print("router modules:", ", ".join(_router_modules()))
    app = _build_app()
    rows = _http_routes(app)
    (DOCS_OUT / "API.md").write_text(_api_md(rows), encoding="utf-8")
    (DOCS_OUT / "ENGINES.md").write_text(_engines_md(), encoding="utf-8")
    (DOCS_OUT / "DATASETS.md").write_text(_datasets_md(), encoding="utf-8")
    print(f"wrote {len(rows)} routes -> docs/API.md, docs/ENGINES.md, docs/DATASETS.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())